# 服务器配置
server:
  host: "127.0.0.1"    # 监听所有网卡
  port: 8080         # 监听端口
  backlog: 1024      # TCP 连接队列大小
  excluded_services: # 不设置代理的网络服务
    - "Thunderbolt Bridge"
    - "Thunderbolt Bridge status"

# 代理应用程序映射配置
proxy_app_map:
  "10.20.30.1:8888":
    - "com.apple.webkit.networking"
    - "code helper (plugin)"
    - "com.docker.backend"

  "127.0.0.1:8081":
    - "firefox"

# 日志配置
logging:
  console:
    enabled: true
    level: info
  file:
    error_log:
      enabled: true
      level: error
      filename: error.log
    warning_log: 
      enabled: true
      level: warn
      filename: warning.log
    combined_log:
      enabled: true
      level: info
      filename: combined.log
    directory: logs
    max_size: 10m
    max_files: 5
